---
title: "" #"l1-phr-tab"
author: "" #"JLAUro"
date: "" #"June 7, 2018"
output: 
  html_document:
    #css: bootstrap/bootstrap-cerulean-grn99.min.css
    #javascript: js/hideshow.js
    #theme: cerulean
    highlight: tango
    #toc: true
    #toc_float: 
    #  collapsed: false
    #mathjax: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
    #mathjax: "file:///sdcard//MathJax/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style>
a, body { 
color: #005500; 
font-size: 12px; 
}	

a:visited { color: #009900; }

[id^='tr'] {
display: none;
}

mark {
padding: 3px 3px;
text-align: left;
font-style: italic;
font-size: 10px;
background-color: #007700;
color: white;
margin-top: 0px;
margin-left: 5px;
}

</style>

<script type='text/javascript'>
function toggle_visibility(id) {
var e = document.getElementById(id);
e.style.display = ((e.style.display!='block') ? 'block' : 'none');
}
</script>

<br/><br/>

<p>
<h4>Lesson 1 Phrase - <a  href=http://www.gutenberg.org/files/8177/8177-h/8177-h.htm>The Esperanto Teacher (by Helen Fryer)</a> <br/></h4>
<a id='r0' href='#' onclick="toggle_visibility('tr0');">
Click for Instructions.</a>
<div id='tr0'>
&nbsp;
<mark>Click on each link to toggle the English translation.  Reload page to turn off all translations.</mark>
</div>
</p>

<table width='100%' border='5px' cellspacing='5px' cellpadding='5px'>
<tr id='r1'>
<td align='center' valign='middle'><a id='item1' href='#r0' onclick="toggle_visibility('tr1');">Leono estas besto. </a>
<div id='tr1'><mark>A lion is an/a animal/beast.</mark></div></td>

<td align='center' valign='middle'><a id='item2' href='#r0' onclick="toggle_visibility('tr2');">Rozo estas floro kaj kolombo estas birdo. </a>
<div id='tr2'><mark>A rose is a flower and a dove/pigeon is a bird.</mark></div></td>

<td align='center' valign='middle'><a id='item3' href='#r0' onclick="toggle_visibility('tr3');">La rozo apartenas al Teodoro. </a>
<div id='tr3'><mark>The rose belongs to Theodore.</mark></div></td>

<td align='center' valign='middle'><a id='item4' href='#r0' onclick="toggle_visibility('tr4');">La suno brilas. </a>
<div id='tr4'><mark>The sun shines.</mark></div></td>
</tr>
<tr id='r2'>

<td align='center' valign='middle'><a id='item5' href='#r1' onclick="toggle_visibility('tr5');">La patro estas tajloro. </a>
<div id='tr5'><mark>The father is a tailor.</mark></div></td>

<td align='center' valign='middle'><a id='item6' href='#r1' onclick="toggle_visibility('tr6');">Kie estas la libro kaj la krajono? </a>
<div id='tr6'><mark>Where are the book and the pencil?</mark></div></td>

<td align='center' valign='middle'><a id='item7' href='#r1' onclick="toggle_visibility('tr7');">Jen estas pomo. </a>
<div id='tr7'><mark>Here is an apple.</mark></div></td>

<td align='center' valign='middle'><a id='item8' href='#r1' onclick="toggle_visibility('tr8');">Sur la tero kuŝas ŝtono. </a>
<div id='tr8'><mark>On the ground/earth lies a stone.</mark></div></td>
</tr>
<tr id='r3'>

<td align='center' valign='middle'><a id='item9' href='#r2' onclick="toggle_visibility('tr9');">Sur la fenestro kuŝas krajono kaj plumo. </a>
<div id='tr9'><mark>On the window lie a pencil and a pen.</mark></div></td>

<td align='center' valign='middle'><a id='item10' href='#r2' onclick="toggle_visibility('tr10');">La filo staras apud la patro. </a>
<div id='tr10'><mark>The son stands beside the father.</mark></div></td>

<td align='center' valign='middle'><a id='item11' href='#r2' onclick="toggle_visibility('tr11');">Jen kuŝas la ĉapelo de la patro. </a>
<div id='tr11'><mark>Here lies the hat of the father.</mark></div></td>

<td align='center' valign='middle'><a id='item12' href='#r2' onclick="toggle_visibility('tr12');">La patro estas en la ĉambro. </a>
<div id='tr12'><mark>The father is in the room.</mark></div></td>
</tr>
<tr id='r4'>

<td align='center' valign='middle'><a id='item13' href='#r3' onclick="toggle_visibility('tr13');">Antaŭ la domo staras arbo.</a>
<div id='tr13'><mark>In front of the house stands a tree.</mark></div></td>

<td align='center' valign='middle'><a id='item14' href='#r3' onclick="toggle_visibility('tr14');">Kio estas leono? </a>
<div id='tr14'><mark>What is a lion?</mark></div></td>

<td align='center' valign='middle'><a id='item15' href='#r3' onclick="toggle_visibility('tr15');">Kio estas rozo? </a>
<div id='tr15'><mark>What is a rose?</mark></div></td>

<td align='center' valign='middle'><a id='item16' href='#r3' onclick="toggle_visibility('tr16');">Kio brilas? </a>
<div id='tr16'><mark>What shines?</mark></div></td>
</tr>
<tr id='r5'>

<td align='center' valign='middle'><a id='item17' href='#r4' onclick="toggle_visibility('tr17');">Kio estas la patro? </a>
<div id='tr17'><mark>What is the father?</mark></div></td>

<td align='center' valign='middle'><a id='item18' href='#r4' onclick="toggle_visibility('tr18');">Kie estas la patro? </a>
<div id='tr18'><mark>Where is the father?</mark></div></td>

<td align='center' valign='middle'><a id='item19' href='#r4' onclick="toggle_visibility('tr19');">Kio estas sur la fenestro? </a>
<div id='tr19'><mark>What is/are (lies/lie) on the window?</mark></div></td>

<td align='center' valign='middle'><a id='item20' href='#r4' onclick="toggle_visibility('tr20');">Kie estas la plumo?</a>
<div id='tr20'><mark>Where is the pen?</mark></div></td>
</tr>
<tr id='r6'>

<td align='center' valign='middle'><a id='item21' href='#r5' onclick="toggle_visibility('tr21');">Ĉu leono estas besto? Jes, leono estas besto. </a>
<div id='tr21'><mark>Is a lion a beast? Yes, a lion is a animal/beast.</mark></div></td>

<td align='center' valign='middle'><a id='item22' href='#r5' onclick="toggle_visibility('tr22');">Ĉu rozo estas birdo? Ne, rozo ne estas birdo, rozo estas floro.</a>
<div id='tr22'><mark>Is a rose a bird? No, a rose is not a bird, a rose is a flower.</mark></div></td>

</tr>
</table>
<br/>
<p>
<a href=addExercises.html>Return to tabular index of Additional Exerices</a>
</p>

