---
title: "" #"l16-phr-tab"
author: "" #"JLAUro"
date: "" #"June 7, 2018"
output: 
  html_document:
    #css: bootstrap/bootstrap-cerulean-grn99.min.css
    #javascript: js/hideshow.js
    #theme: cerulean
    highlight: tango
    #toc: true
    #toc_float: 
    #  collapsed: false
    #mathjax: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
    #mathjax: "file:///sdcard//MathJax/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style>
a, body { 
color: #005500; 
font-size: 12px; 
}	

a:visited { color: #009900; }

[id^='tr'] {
display: none;
}

mark {
padding: 3px 3px;
text-align: left;
font-style: italic;
font-size: 10px;
background-color: #007700;
color: white;
margin-top: 0px;
margin-left: 5px;
}

</style>

<script type='text/javascript'>
function toggle_visibility(id) {
var e = document.getElementById(id);
e.style.display = ((e.style.display!='block') ? 'block' : 'none');
}
</script>

<br/><br/>

<p>
<h4>Lesson 16 Phrase - <a href=http://www.gutenberg.org/files/8177/8177-h/8177-h.htm>The Esperanto Teacher (by Helen Fryer)</a> <br/></h4>
<a id='r0' href='#' onclick="toggle_visibility('tr0');">
Click for Instructions.</a>
<div id='tr0'>
&nbsp;
<mark>Click on each link to toggle the English translation.  Reload page to turn off all translations.</mark>
</div>
</p>

<table width='100%' border='5px' cellspacing='5px' cellpadding='5px'>
<tr id='r1'>
<td align='center' valign='middle'><a id='item1' href='#r0' onclick="toggle_visibility('tr1');">Fluanta akvo estas pli pura, ol akvo staranta senmove.</a>
<div id='tr1'><mark>Flowing water is purer than water standing still.</mark></div></td>

<td align='center' valign='middle'><a id='item2' href='#r0' onclick="toggle_visibility('tr2');">La falinta homo ne povas sin levi.</a>
<div id='tr2'><mark>The fallen man cannot raise himself.</mark></div></td>

<td align='center' valign='middle'><a id='item3' href='#r0' onclick="toggle_visibility('tr3');">La tempo pasinta jam neniam revenos; la tempon venontan neniu ankoraŭ konas.</a>
<div id='tr3'><mark>(The) time past will never more return; (the) time to come no one yet knows.</mark></div></td>

<td align='center' valign='middle'><a id='item4' href='#r0' onclick="toggle_visibility('tr4');">Venu, ni atendas vin, Savonto de la mondo.</a>
<div id='tr4'><mark>Come, we await you, Saviour of the world.</mark></div></td>
</tr>
<tr id='r2'>

<td align='center' valign='middle'><a id='item5' href='#r1' onclick="toggle_visibility('tr5');">En la lingvo Esperanto ni vidas la estontan lingvon de la tuta mondo.</a>
<div id='tr5'><mark>In the language Esperanto we see the future language of the whole world.</mark></div></td>

<td align='center' valign='middle'><a id='item6' href='#r1' onclick="toggle_visibility('tr6');">La nombro de la dancantoj estis granda.</a>
<div id='tr6'><mark>The number of the dancers was great.</mark></div></td>

<td align='center' valign='middle'><a id='item7' href='#r1' onclick="toggle_visibility('tr7');">Ĝi estas la legendo, kiun la veraj kredantoj ĉiam ripetas.</a>
<div id='tr7'><mark>It is the legend which true believers always repeat.</mark></div></td>

<td align='center' valign='middle'><a id='item8' href='#r1' onclick="toggle_visibility('tr8');">Li kondukis la vojaĝanton al la loko, kie la ŝtelintoj ripozis.</a>
<div id='tr8'><mark>He led the traveller to the place where the thieves were resting.</mark></div></td>
</tr>
<tr id='r3'>

<td align='center' valign='middle'><a id='item9' href='#r2' onclick="toggle_visibility('tr9');">Al homo, pekinta senintence, Dio facile pardonas.</a>
<div id='tr9'><mark>(To) a man who has sinned unintentionally God easily pardons.</mark></div></td>

<td align='center' valign='middle'><a id='item10' href='#r2' onclick="toggle_visibility('tr10');">La soldatoj kondukis la arestitojn tra la stratoj.</a>
<div id='tr10'><mark>The soldiers led the prisoners (arrested) through the streets.</mark></div></td>

<td align='center' valign='middle'><a id='item11' href='#r2' onclick="toggle_visibility('tr11');">Homo, kiun oni devas juĝi, estas juĝoto.</a>
<div id='tr11'><mark>A man whom one has to judge is one to be judged (prisoner at the bar).</mark></div></td>

<td align='center' valign='middle'><a id='item12' href='#r2' onclick="toggle_visibility('tr12');">Nun li diras al mi la veron.</a>
<div id='tr12'><mark>Now he teils me the truth.</mark></div></td>
</tr>
<tr id='r4'>

<td align='center' valign='middle'><a id='item13' href='#r3' onclick="toggle_visibility('tr13');">Hieraŭ li diris al mi la veron.</a>
<div id='tr13'><mark>Yesterday he told me the truth.</mark></div></td>

<td align='center' valign='middle'><a id='item14' href='#r3' onclick="toggle_visibility('tr14');">Li ĉiam diradis al mi la veron.</a>
<div id='tr14'><mark>He always told me the truth.</mark></div></td>

<td align='center' valign='middle'><a id='item15' href='#r3' onclick="toggle_visibility('tr15');">Kiam vi vidis nin en la salono, li jam antaŭe diris al mi la veron (aŭ, li estis dirinta al mi la veron).</a>
<div id='tr15'><mark>When you saw us in the drawing-room he had already (previously) told me the truth.</mark></div></td>

<td align='center' valign='middle'><a id='item16' href='#r3' onclick="toggle_visibility('tr16');">Li diros al mi la veron.</a>
<div id='tr16'><mark>He will tell me the truth.</mark></div></td>
</tr>
<tr id='r5'>

<td align='center' valign='middle'><a id='item17' href='#r4' onclick="toggle_visibility('tr17');">Kiam vi venos al mi, li jam antaŭe diros al mi la veron (aŭ, li estos dirinta al mi la veron; aŭ, antaŭ ol vi venos al mi, li diros al mi la veron).</a>
<div id='tr17'><mark>When you (shall) come to me, he will previously tell me the truth (or, he will have told me the truth; or, before you (will) come to me, he will tell me the truth).</mark></div></td>

<td align='center' valign='middle'><a id='item18' href='#r4' onclick="toggle_visibility('tr18');">Se mi petus lin, li dirus al mi la veron.</a>
<div id='tr18'><mark>If I were to ask him, he would tell me the truth.</mark></div></td>

<td align='center' valign='middle'><a id='item19' href='#r4' onclick="toggle_visibility('tr19');">Mi ne farus la eraron, se li antaŭe dirus al mi la veron (aŭ, se li estus dirinta al mi la veron).</a>
<div id='tr19'><mark>I should not have made the mistake if he had previously told me the truth.</mark></div></td>

<td align='center' valign='middle'><a id='item20' href='#r4' onclick="toggle_visibility('tr20');">Kiam mi venos, diru al mi la veron.</a>
<div id='tr20'><mark>When I (shall) come, tell me the truth.</mark></div></td>
</tr>
<tr id='r6'>

<td align='center' valign='middle'><a id='item21' href='#r5' onclick="toggle_visibility('tr21');">Kiam mia patro venos, diru al mi antaŭe la veron (aŭ, estu dirinta al mi la veron).</a>
<div id='tr21'><mark>When my father (shall) come, tell me beforehand the truth. I wish to tell you the truth. I wish that that which I said should be true (or, I wish to have told the truth).</mark></div></td>

<td align='center' valign='middle'><a id='item22' href='#r5' onclick="toggle_visibility('tr22');">Mi volas diri al vi la veron.</a>
<div id='tr22'><mark>I wish to tell you the truth.</mark></div></td>

<td align='center' valign='middle'><a id='item23' href='#r5' onclick="toggle_visibility('tr23');">Mi volas, ke tio, kion mi diris, estu vera (aŭ, mi volas esti dirinta la veron).</a>
<div id='tr23'><mark>I wish that that which I said should be true (or, I wish to have told the truth).</mark></div></td>

</tr>
</table>
<br/>
<p>
<a href=addExercises.html>Return to tabular index of Additional Exerices</a>
</p>

