---
title: "" #"l18-phr-tab"
author: "" #"JLAUro"
date: "" #"June 7, 2018"
output: 
  html_document:
    #css: bootstrap/bootstrap-cerulean-grn99.min.css
    #javascript: js/hideshow.js
    #theme: cerulean
    highlight: tango
    #toc: true
    #toc_float: 
    #  collapsed: false
    #mathjax: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
    #mathjax: "file:///sdcard//MathJax/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style>
a, body { 
color: #005500; 
font-size: 12px; 
}	

a:visited { color: #009900; }

[id^='tr'] {
display: none;
}

mark {
padding: 3px 3px;
text-align: left;
font-style: italic;
font-size: 10px;
background-color: #007700;
color: white;
margin-top: 0px;
margin-left: 5px;
}

</style>

<script type='text/javascript'>
function toggle_visibility(id) {
var e = document.getElementById(id);
e.style.display = ((e.style.display!='block') ? 'block' : 'none');
}
</script>

<br/><br/>

<p>
<h4>Lesson 18 Phrase - <a href=http://www.gutenberg.org/files/8177/8177-h/8177-h.htm>The Esperanto Teacher (by Helen Fryer)</a> <br/></h4>
<a id='r0' href='#' onclick="toggle_visibility('tr0');">
Click for Instructions.</a>
<div id='tr0'>
&nbsp;
<mark>Click on each link to toggle the English translation.  Reload page to turn off all translations.</mark>
</div>
</p>

<table width='100%' border='5px' cellspacing='5px' cellpadding='5px'>
<tr id='r1'>
<td align='center' valign='middle'><a id='item1' href='#r0' onclick="toggle_visibility('tr1');">La botisto faras botojn kaj ŝuojn.</a>
<div id='tr1'><mark>The bootmaker makes boots and shoes.</mark></div></td>

<td align='center' valign='middle'><a id='item2' href='#r0' onclick="toggle_visibility('tr2');">Ŝtelistojn neniu lasas en sian domon.</a>
<div id='tr2'><mark>Nobody lets thieves into his house.</mark></div></td>

<td align='center' valign='middle'><a id='item3' href='#r0' onclick="toggle_visibility('tr3');">La kuraĝa maristo dronis en la maro.</a>
<div id='tr3'><mark>The brave sailor was drowned in the sea.</mark></div></td>

<td align='center' valign='middle'><a id='item4' href='#r0' onclick="toggle_visibility('tr4');">Verkisto verkas librojn, kaj skribisto simple transskribas paperojn.</a>
<div id='tr4'><mark>An author writes books, and a writer simply copies papers.</mark></div></td>
</tr>
<tr id='r2'>

<td align='center' valign='middle'><a id='item5' href='#r1' onclick="toggle_visibility('tr5');">Ni havas diversajn servantojn—kuiriston, ĉambristinon, infanistinon, kaj veturigiston.</a>
<div id='tr5'><mark>We have various servants - a cook, a housemaid, a nurse, and a coachman.</mark></div></td>

<td align='center' valign='middle'><a id='item6' href='#r1' onclick="toggle_visibility('tr6');">Kiu okupas sin je meĥaniko estas meĥankisto, kaj kiu okupas sin je ĥemio estas ĥemiisto.</a>
<div id='tr6'><mark>(He) who occupies himself with mechanics is a mechanic, and (he) who occupies himself with chemistry is a chemist.</mark></div></td>

<td align='center' valign='middle'><a id='item7' href='#r1' onclick="toggle_visibility('tr7');">Diplomatiiston oni povas ankaŭ nomi diplomato, [Footnote: See Lesson 45.] sed fizikiston oni ne povas nomi fiziko, [Footnote: See Lesson 45.] ĉar fiziko estas la nomo de la scienco mem.</a>
<div id='tr7'><mark>A diplomatist we can also call a diplomat, but a physicist we cannot call a “physic,” for “physics” is the name of the science itself.</mark></div></td>

<td align='center' valign='middle'><a id='item8' href='#r1' onclick="toggle_visibility('tr8');">Unu tagon [Footnote: See Lesson 26.] (en unu tago) venis du trompantoj, kiuj diris, ke ili estas teksistoj.</a>
<div id='tr8'><mark>One day there came two cheats, who said that they were (are) weavers.</mark></div></td>
</tr>
<tr id='r3'>

</tr>
</table>
<br/>
<p>
<a href=addExercises.html>Return to tabular index of Additional Exerices</a>
</p>

