---
title: "" #"l20-phr-tab"
author: "" #"JLAUro"
date: "" #"June 7, 2018"
output: 
  html_document:
    #css: bootstrap/bootstrap-cerulean-grn99.min.css
    #javascript: js/hideshow.js
    #theme: cerulean
    highlight: tango
    #toc: true
    #toc_float: 
    #  collapsed: false
    #mathjax: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
    #mathjax: "file:///sdcard//MathJax/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style>
a, body { 
color: #005500; 
font-size: 12px; 
}	

a:visited { color: #009900; }

[id^='tr'] {
display: none;
}

mark {
padding: 3px 3px;
text-align: left;
font-style: italic;
font-size: 10px;
background-color: #007700;
color: white;
margin-top: 0px;
margin-left: 5px;
}

</style>

<script type='text/javascript'>
function toggle_visibility(id) {
var e = document.getElementById(id);
e.style.display = ((e.style.display!='block') ? 'block' : 'none');
}
</script>

<br/><br/>

<p>
<h4>Lesson 20 Phrase - <a href=http://www.gutenberg.org/files/8177/8177-h/8177-h.htm>The Esperanto Teacher (by Helen Fryer)</a> <br/></h4>
<a id='r0' href='#' onclick="toggle_visibility('tr0');">
Click for Instructions.</a>
<div id='tr0'>
&nbsp;
<mark>Click on each link to toggle the English translation.  Reload page to turn off all translations.</mark>
</div>
</p>

<table width='100%' border='5px' cellspacing='5px' cellpadding='5px'>
<tr id='r1'>
<td align='center' valign='middle'><a id='item1' href='#r0' onclick="toggle_visibility('tr1');">La maro estas tie pli profunda, ol povas atingi ia ankro.</a>
<div id='tr1'><mark>The sea is deeper there than any anchor can reach.</mark></div></td>

<td align='center' valign='middle'><a id='item2' href='#r0' onclick="toggle_visibility('tr2');">En ia maniero.</a>
<div id='tr2'><mark>In some (any) way.</mark></div></td>

<td align='center' valign='middle'><a id='item3' href='#r0' onclick="toggle_visibility('tr3');">Sen ia riproĉo de konscienco.</a>
<div id='tr3'><mark>Without any reproach of conscience.</mark></div></td>

<td align='center' valign='middle'><a id='item4' href='#r0' onclick="toggle_visibility('tr4');">Mi scias, en kia loko mi certe lin trovos.</a>
<div id='tr4'><mark>I know in what sort of place I shall certainly find him.</mark></div></td>
</tr>
<tr id='r2'>

<td align='center' valign='middle'><a id='item5' href='#r1' onclick="toggle_visibility('tr5');">Kia estas la vetero?</a>
<div id='tr5'><mark>What kind of weather is it?</mark></div></td>

<td align='center' valign='middle'><a id='item6' href='#r1' onclick="toggle_visibility('tr6');">Kian malbonon mi al vi faris?</a>
<div id='tr6'><mark>What harm have I done to you?</mark></div></td>

<td align='center' valign='middle'><a id='item7' href='#r1' onclick="toggle_visibility('tr7');">Tiamaniere li faris ĉion.</a>
<div id='tr7'><mark>In that way he did everything.</mark></div></td>

<td align='center' valign='middle'><a id='item8' href='#r1' onclick="toggle_visibility('tr8');">Li invitis lin veni en tian kaj tian lokon.</a>
<div id='tr8'><mark>He invited him to come into such and such a place.</mark></div></td>
</tr>
<tr id='r3'>

<td align='center' valign='middle'><a id='item9' href='#r2' onclick="toggle_visibility('tr9');">Ne ĉia birdo kantas.</a>
<div id='tr9'><mark>Not every sort of bird sings.</mark></div></td>

<td align='center' valign='middle'><a id='item10' href='#r2' onclick="toggle_visibility('tr10');">Ekster ĉia dubo.</a>
<div id='tr10'><mark>Beyond all doubt.</mark></div></td>

<td align='center' valign='middle'><a id='item11' href='#r2' onclick="toggle_visibility('tr11');">Nenia homo meritas tian punon.</a>
<div id='tr11'><mark>No (kind of) man deserves such a punishment.</mark></div></td>

<td align='center' valign='middle'><a id='item12' href='#r2' onclick="toggle_visibility('tr12');">Tiaj libroj estas malutilaj.</a>
<div id='tr12'><mark>Such books are harmful.</mark></div></td>
</tr>
<tr id='r4'>

<td align='center' valign='middle'><a id='item13' href='#r3' onclick="toggle_visibility('tr13');">Iafoje li vizitas nin.</a>
<div id='tr13'><mark>At times he visits us.</mark></div></td>

<td align='center' valign='middle'><a id='item14' href='#r3' onclick="toggle_visibility('tr14');">Ial li ne povis dormi.</a>
<div id='tr14'><mark>For some reason he could not sleep.</mark></div></td>

<td align='center' valign='middle'><a id='item15' href='#r3' onclick="toggle_visibility('tr15');">Kial vi ne respondas al mi?</a>
<div id='tr15'><mark>Why do you not answer me?</mark></div></td>

<td align='center' valign='middle'><a id='item16' href='#r3' onclick="toggle_visibility('tr16');">Mi ne komprenis vian demandon, tial mi ne respondis.</a>
<div id='tr16'><mark>I did not understand your question, therefore I did not answer.</mark></div></td>
</tr>
<tr id='r5'>

<td align='center' valign='middle'><a id='item17' href='#r4' onclick="toggle_visibility('tr17');">La homoj ne komprenas unu la alian, kaj tial ili tenas sin fremde.</a>
<div id='tr17'><mark>People do not understand one another, and therefore they hold themselves aloof.</mark></div></td>

<td align='center' valign='middle'><a id='item18' href='#r4' onclick="toggle_visibility('tr18');">Ĉial tio estas la plej bona.</a>
<div id='tr18'><mark>For every reason that is the best.</mark></div></td>

<td align='center' valign='middle'><a id='item19' href='#r4' onclick="toggle_visibility('tr19');">Mi iam vin amis.</a>
<div id='tr19'><mark>I once loved you.</mark></div></td>

<td align='center' valign='middle'><a id='item20' href='#r4' onclick="toggle_visibility('tr20');">Kio vivas, necese devas iam morti.</a>
<div id='tr20'><mark>What lives must of necessity some time die.</mark></div></td>
</tr>
<tr id='r6'>

<td align='center' valign='middle'><a id='item21' href='#r5' onclick="toggle_visibility('tr21');">Kiam vi foriros?</a>
<div id='tr21'><mark>When shall you go away?</mark></div></td>

<td align='center' valign='middle'><a id='item22' href='#r5' onclick="toggle_visibility('tr22');">En la luna nokto, kiam ĉiuj dormis, tiam ŝi sidis sur la rando de la ŝipo.</a>
<div id='tr22'><mark>In the moonlight night, when all were asleep, then she sat on the edge or the ship.</mark></div></td>

<td align='center' valign='middle'><a id='item23' href='#r5' onclick="toggle_visibility('tr23');">Estu por ĉiam benata!</a>
<div id='tr23'><mark>Be for ever blessed!</mark></div></td>

<td align='center' valign='middle'><a id='item24' href='#r5' onclick="toggle_visibility('tr24');">Ŝi antaŭe neniam vidis hundon.</a>
<div id='tr24'><mark>She had never seen a dog before.</mark></div></td>
</tr>
<tr id='r7'>

<td align='center' valign='middle'><a id='item25' href='#r6' onclick="toggle_visibility('tr25');">Kie estas la knaboj?</a>
<div id='tr25'><mark>Where are the boys?</mark></div></td>

<td align='center' valign='middle'><a id='item26' href='#r6' onclick="toggle_visibility('tr26');">Kien vi iris?</a>
<div id='tr26'><mark>Where did you go?</mark></div></td>

<td align='center' valign='middle'><a id='item27' href='#r6' onclick="toggle_visibility('tr27');">Mi restas tie ĉi.</a>
<div id='tr27'><mark>I am staying here.</mark></div></td>

<td align='center' valign='middle'><a id='item28' href='#r6' onclick="toggle_visibility('tr28');">Li perdis sian monujon ie en la urbo, sed kie li perdis ĝin, li ne scias.</a>
<div id='tr28'><mark>He lost his purse somewhere in the town, but where he lost it he does not know.</mark></div></td>
</tr>
<tr id='r8'>

<td align='center' valign='middle'><a id='item29' href='#r7' onclick="toggle_visibility('tr29');">Mi volonte el tie venis tien ĉi.</a>
<div id='tr29'><mark>I willingly came from there here.</mark></div></td>

<td align='center' valign='middle'><a id='item30' href='#r7' onclick="toggle_visibility('tr30');">Li petis ŝin, ke ŝi diru al li, de kie si venas. [Footnote: See note in Lesson 17.]</a>
<div id='tr30'><mark>He begged her to tell him whence she came (whence she comes).</mark></div></td>

<td align='center' valign='middle'><a id='item31' href='#r7' onclick="toggle_visibility('tr31');">Por la juneco ĉie staras retoj.</a>
<div id='tr31'><mark>For youth there are snares everywhere.</mark></div></td>

<td align='center' valign='middle'><a id='item32' href='#r7' onclick="toggle_visibility('tr32');">Ĉie estas floroj, kaj nenie oni povas trovi pli belajn.</a>
<div id='tr32'><mark>Everywhere are flowers, and nowhere can one find more beautiful (ones).</mark></div></td>
</tr>
<tr id='r9'>

<td align='center' valign='middle'><a id='item33' href='#r8' onclick="toggle_visibility('tr33');">Kiel bela!</a>
<div id='tr33'><mark>How beautiful!</mark></div></td>

<td align='center' valign='middle'><a id='item34' href='#r8' onclick="toggle_visibility('tr34');">Ĉu mi taŭgas kiel reĝo?</a>
<div id='tr34'><mark>Am I fit for a king?</mark></div></td>

<td align='center' valign='middle'><a id='item35' href='#r8' onclick="toggle_visibility('tr35');">Tiel finiĝis la feliĉa tago.</a>
<div id='tr35'><mark>So finished the happy day.</mark></div></td>

<td align='center' valign='middle'><a id='item36' href='#r8' onclick="toggle_visibility('tr36');">Ili brilis kiel diamantoj.</a>
<div id='tr36'><mark>They shone like diamonds.</mark></div></td>
</tr>
<tr id='r10'>

<td align='center' valign='middle'><a id='item37' href='#r9' onclick="toggle_visibility('tr37');">Kiel vi fartas?</a>
<div id='tr37'><mark>How are you?</mark></div></td>

<td align='center' valign='middle'><a id='item38' href='#r9' onclick="toggle_visibility('tr38');">Iel li malkomprenis min.</a>
<div id='tr38'><mark>Somehow he misunderstood me.</mark></div></td>

<td align='center' valign='middle'><a id='item39' href='#r9' onclick="toggle_visibility('tr39');">Mia edzino pensis tiel same, kiel mi.</a>
<div id='tr39'><mark>My wife thought the same as I.</mark></div></td>

<td align='center' valign='middle'><a id='item40' href='#r9' onclick="toggle_visibility('tr40');">Mi neniel povas kompreni, kion vi diras.</a>
<div id='tr40'><mark>I cannot understand at all what you say.</mark></div></td>
</tr>
<tr id='r11'>

<td align='center' valign='middle'><a id='item41' href='#r10' onclick="toggle_visibility('tr41');">Tre stranga kaj neniel komprenebla!</a>
<div id='tr41'><mark>Very strange and quite incomprehensible!</mark></div></td>

<td align='center' valign='middle'><a id='item42' href='#r10' onclick="toggle_visibility('tr42');">Mi elektis lin kiel prezidanto.</a>
<div id='tr42'><mark>I, as president, elected him.</mark></div></td>

<td align='center' valign='middle'><a id='item43' href='#r10' onclick="toggle_visibility('tr43');">Mi elektis lin kiel prezidanton.</a>
<div id='tr43'><mark>I chose him as president.</mark></div></td>

<td align='center' valign='middle'><a id='item44' href='#r10' onclick="toggle_visibility('tr44');">Kies ganto tiu ĉi estas?</a>
<div id='tr44'><mark>Whose glove is this?</mark></div></td>
</tr>
<tr id='r12'>

<td align='center' valign='middle'><a id='item45' href='#r11' onclick="toggle_visibility('tr45');">Mi neniam alprenas ties opinion.</a>
<div id='tr45'><mark>I never take that one’s opinion.</mark></div></td>

<td align='center' valign='middle'><a id='item46' href='#r11' onclick="toggle_visibility('tr46');">Subite ŝi ekaŭdis ies fortan malagrablan voĉon.</a>
<div id='tr46'><mark>Suddenly she heard somebody’s loud disagreeable voice.</mark></div></td>

<td align='center' valign='middle'><a id='item47' href='#r11' onclick="toggle_visibility('tr47');">Ĉies ideo estas diversa.</a>
<div id='tr47'><mark>Everybody’s idea is different.</mark></div></td>

<td align='center' valign='middle'><a id='item48' href='#r11' onclick="toggle_visibility('tr48');">Bona amiko, sen kies helpo li neniam ekvidus tiun ĉi landon.</a>
<div id='tr48'><mark>A good friend, without whose help he would never have seen this land.</mark></div></td>
</tr>
<tr id='r13'>

<td align='center' valign='middle'><a id='item49' href='#r12' onclick="toggle_visibility('tr49');">Ies perdo ne estas ĉiam ies gajno.</a>
<div id='tr49'><mark>Somebody’s loss is not always somebody’s gain.</mark></div></td>

<td align='center' valign='middle'><a id='item50' href='#r12' onclick="toggle_visibility('tr50');">Ies perdo estas ofte nenies gajno.</a>
<div id='tr50'><mark>Someone’s loss is often no one’s gain.</mark></div></td>

<td align='center' valign='middle'><a id='item51' href='#r12' onclick="toggle_visibility('tr51');">Mi sentas, ke io okazas.</a>
<div id='tr51'><mark>I feel that something is happening.</mark></div></td>

<td align='center' valign='middle'><a id='item52' href='#r12' onclick="toggle_visibility('tr52');">Neniam mi ion al vi donis.</a>
<div id='tr52'><mark>Never did I give you anything.</mark></div></td>
</tr>
<tr id='r14'>

<td align='center' valign='middle'><a id='item53' href='#r13' onclick="toggle_visibility('tr53');">Mi volas fari al vi ion bonan.</a>
<div id='tr53'><mark>I wish to do something good for (to) you.</mark></div></td>

<td align='center' valign='middle'><a id='item54' href='#r13' onclick="toggle_visibility('tr54');">Kio tio ĉi estas?</a>
<div id='tr54'><mark>What is this?</mark></div></td>

<td align='center' valign='middle'><a id='item55' href='#r13' onclick="toggle_visibility('tr55');">Kia ornamo tiu ĉi estas?</a>
<div id='tr55'><mark>What kind of ornament is this?</mark></div></td>

<td align='center' valign='middle'><a id='item56' href='#r13' onclick="toggle_visibility('tr56');">Kion mi vidas?</a>
<div id='tr56'><mark>What do I see?</mark></div></td>
</tr>
<tr id='r15'>

<td align='center' valign='middle'><a id='item57' href='#r14' onclick="toggle_visibility('tr57');">Tio ĉi estas ĉio, pri kio mi parolis.</a>
<div id='tr57'><mark>This is all I spoke of.</mark></div></td>

<td align='center' valign='middle'><a id='item58' href='#r14' onclick="toggle_visibility('tr58');">Mi nenion cedos al vi.</a>
<div id='tr58'><mark>I will give up nothing to you.</mark></div></td>

<td align='center' valign='middle'><a id='item59' href='#r14' onclick="toggle_visibility('tr59');">Nenion faru kontraŭ la patrino.</a>
<div id='tr59'><mark>Do nothing against your mother.</mark></div></td>

<td align='center' valign='middle'><a id='item60' href='#r14' onclick="toggle_visibility('tr60');">Antaŭ ĉio estu fidela al vi mem.</a>
<div id='tr60'><mark>Before all, be faithful to yourself.</mark></div></td>
</tr>
<tr id='r16'>

<td align='center' valign='middle'><a id='item61' href='#r15' onclick="toggle_visibility('tr61');">Ŝi eksentis ion tian, kion ŝi mem komence ne povas kompreni.</a>
<div id='tr61'><mark>She began to feel something such as (which) she herself in the beginning could (can) not understand.</mark></div></td>

<td align='center' valign='middle'><a id='item62' href='#r15' onclick="toggle_visibility('tr62');">Ŝi parolis iom kolere.</a>
<div id='tr62'><mark>She spoke a little angrily.</mark></div></td>

<td align='center' valign='middle'><a id='item63' href='#r15' onclick="toggle_visibility('tr63');">La pupiloj de la okuloj iom post iom malgrandiĝis.</a>
<div id='tr63'><mark>The pupils of the eyes little by little contracted.</mark></div></td>

<td align='center' valign='middle'><a id='item64' href='#r15' onclick="toggle_visibility('tr64');">Kiu estas tiom senprudenta, ke li povas ĝin kredi?</a>
<div id='tr64'><mark>Who is so unreasonable (senseless) that he can believe it?</mark></div></td>
</tr>
<tr id='r17'>

<td align='center' valign='middle'><a id='item65' href='#r16' onclick="toggle_visibility('tr65');">Kiom da mono vi havas?</a>
<div id='tr65'><mark>How much money have you?</mark></div></td>

<td align='center' valign='middle'><a id='item66' href='#r16' onclick="toggle_visibility('tr66');">Mi havas neniom.</a>
<div id='tr66'><mark>I have none.</mark></div></td>

<td align='center' valign='middle'><a id='item67' href='#r16' onclick="toggle_visibility('tr67');">Donu al mi tiom da akvo, kiom da vino.</a>
<div id='tr67'><mark>Give me as much water as wine.</mark></div></td>

<td align='center' valign='middle'><a id='item68' href='#r16' onclick="toggle_visibility('tr68');">Iu venas; kiu ĝi estas?</a>
<div id='tr68'><mark>Somebody comes; who is it?</mark></div></td>
</tr>
<tr id='r18'>

<td align='center' valign='middle'><a id='item69' href='#r17' onclick="toggle_visibility('tr69');">Ĉu iu kuraĝus tion fari?</a>
<div id='tr69'><mark>Would anybody have the courage to do that?</mark></div></td>

<td align='center' valign='middle'><a id='item70' href='#r17' onclick="toggle_visibility('tr70');">Ĉiu penis sin savi, kiel li povis.</a>
<div id='tr70'><mark>Everybody tried to save himself as he could.</mark></div></td>

<td align='center' valign='middle'><a id='item71' href='#r17' onclick="toggle_visibility('tr71');">Lingvo, en kiu neniu nin komprenos.</a>
<div id='tr71'><mark>A language in which nobody will understand us.</mark></div></td>

<td align='center' valign='middle'><a id='item72' href='#r17' onclick="toggle_visibility('tr72');">Neniu el ili povis savi la dronanton.</a>
<div id='tr72'><mark>None of them could save the drowning person.</mark></div></td>
</tr>
<tr id='r19'>

<td align='center' valign='middle'><a id='item73' href='#r18' onclick="toggle_visibility('tr73');">Li al neniu helpis iam eĉ per unu centimo.</a>
<div id='tr73'><mark>He helped nobody ever (never helped anybody) even with one centime.</mark></div></td>

<td align='center' valign='middle'><a id='item74' href='#r18' onclick="toggle_visibility('tr74');">Ni iros ĉiuj kune.</a>
<div id='tr74'><mark>We shall go all together.</mark></div></td>

<td align='center' valign='middle'><a id='item75' href='#r18' onclick="toggle_visibility('tr75');">Mi konas neniun en tiu urbo.</a>
<div id='tr75'><mark>I know nobody in that town.</mark></div></td>

<td align='center' valign='middle'><a id='item76' href='#r18' onclick="toggle_visibility('tr76');">Tio ĉi estas super ĉiuj homaj fortoj.</a>
<div id='tr76'><mark>This is beyond all human strength.</mark></div></td>
</tr>
<tr id='r20'>

<td align='center' valign='middle'><a id='item77' href='#r19' onclick="toggle_visibility('tr77');">De kie mi veturas, kien kaj pro kio, mi nur povas respondi: mi ne scias.</a>
<div id='tr77'><mark>Where I am travelling from, whither and why, I can only answer: I know not.</mark></div></td>

<td align='center' valign='middle'><a id='item78' href='#r19' onclick="toggle_visibility('tr78');">Oni petis lin atendi iom kun lia forveturo.</a>
<div id='tr78'><mark>They begged him to delay a little (with) his departure.</mark></div></td>

<td align='center' valign='middle'><a id='item79' href='#r19' onclick="toggle_visibility('tr79');">Tiuj ĉi nestoj ofte estas pli grandaj, ol la dometoj de la tieaj homoj.</a>
<div id='tr79'><mark>These nests are often larger than the huts of the people of that place.</mark></div></td>

<td align='center' valign='middle'><a id='item80' href='#r19' onclick="toggle_visibility('tr80');">Li forveturis kun firma decido forlasi por ĉiam tiun ĉi sendankan landon.</a>
<div id='tr80'><mark>He departed with the firm resolve to leave for ever this ungrateful land.</mark></div></td>
</tr>
<tr id='r21'>

<td align='center' valign='middle'><a id='item81' href='#r20' onclick="toggle_visibility('tr81');">Se iu tion vidus, li malbenus la Fortunon.</a>
<div id='tr81'><mark>If anyone were to see that, he would curse Fortune.</mark></div></td>

<td align='center' valign='middle'><a id='item82' href='#r20' onclick="toggle_visibility('tr82');">Mi donus cent funtojn sterlingajn, se bova lango povus havi por mi tian bonan guston kiel por vi.</a>
<div id='tr82'><mark>I would give a hundred pounds sterling if ox tongue could have for me such a good taste as for you.</mark></div></td>

<td align='center' valign='middle'><a id='item83' href='#r20' onclick="toggle_visibility('tr83');">Kioma horo (estas)?</a>
<div id='tr83'><mark>What time is it?</mark></div></td>

<td align='center' valign='middle'><a id='item84' href='#r20' onclick="toggle_visibility('tr84');">Baldaŭ la dekdua (horo).</a>
<div id='tr84'><mark>Nearly (soon) twelve o’clock.</mark></div></td>
</tr>
<tr id='r22'>

</tr>
</table>
<br/>
<p>
<a href=addExercises.html>Return to tabular index of Additional Exerices</a>
</p>

