---
title: "" #"l5-phr-tab"
author: "" #"JLAUro"
date: "" #"June 7, 2018"
output: 
  html_document:
    #css: bootstrap/bootstrap-cerulean-grn99.min.css
    #javascript: js/hideshow.js
    #theme: cerulean
    highlight: tango
    #toc: true
    #toc_float: 
    #  collapsed: false
    #mathjax: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
    #mathjax: "file:///sdcard//MathJax/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style>
a, body { 
color: #005500; 
font-size: 12px; 
}	

a:visited { color: #009900; }

[id^='tr'] {
display: none;
}

mark {
padding: 3px 3px;
text-align: left;
font-style: italic;
font-size: 10px;
background-color: #007700;
color: white;
margin-top: 0px;
margin-left: 5px;
}

</style>

<script type='text/javascript'>
function toggle_visibility(id) {
var e = document.getElementById(id);
e.style.display = ((e.style.display!='block') ? 'block' : 'none');
}
</script>

<br/><br/>

<p>
<h4>Lesson 5 Vocabulary  - <a  href=http://www.gutenberg.org/files/8177/8177-h/8177-h.htm>The Esperanto Teacher (by Helen Fryer)</a> <br/></h4>
<a id='r0' href='#' onclick="toggle_visibility('tr0');">
Click for Instructions.</a>
<div id='tr0'>
&nbsp;
<mark>Click on each link to toggle the English translation.  Reload page to turn off all translations.</mark>
</div>
</p>

<table width='100%' border='5px' cellspacing='5px' cellpadding='5px'>
<tr id='r1'>
<td align='center' valign='middle'><a id='item1' href='#r0' onclick="toggle_visibility('tr1');">Mi vidas leonon (leonojn). </a>
<div id='tr1'><mark>I see a lion (lions).</mark></div></td>

<td align='center' valign='middle'><a id='item2' href='#r0' onclick="toggle_visibility('tr2');">Mi legas libron (librojn). </a>
<div id='tr2'><mark>I read (am reading) a book (books).</mark></div></td>

<td align='center' valign='middle'><a id='item3' href='#r0' onclick="toggle_visibility('tr3');">Mi amas la patron. </a>
<div id='tr3'><mark>I love the father.</mark></div></td>

<td align='center' valign='middle'><a id='item4' href='#r0' onclick="toggle_visibility('tr4');">Mi konas Johanon. </a>
<div id='tr4'><mark>I know John.</mark></div></td>
</tr>
<tr id='r2'>

<td align='center' valign='middle'><a id='item5' href='#r1' onclick="toggle_visibility('tr5');">La patro ne legas libron, sed li skribas leteron. </a>
<div id='tr5'><mark>The father is not reading the book but he is writing a letter.</mark></div></td>

<td align='center' valign='middle'><a id='item6' href='#r1' onclick="toggle_visibility('tr6');">Mi ne amas obstinajn homojn. </a>
<div id='tr6'><mark>I do not love hard-headed men.</mark></div></td>

<td align='center' valign='middle'><a id='item7' href='#r1' onclick="toggle_visibility('tr7');">Mi deziras al vi bonan tagon, sinjoro. </a>
<div id='tr7'><mark>I wish a good day to you, Sir.</mark></div></td>

<td align='center' valign='middle'><a id='item8' href='#r1' onclick="toggle_visibility('tr8');">Bonan matenon! Ĝojan feston (mi deziras al vi). </a>
<div id='tr8'><mark>Good morning! A joyful holiday (I wish [to] you).</mark></div></td>
</tr>
<tr id='r3'>

<td align='center' valign='middle'><a id='item9' href='#r2' onclick="toggle_visibility('tr9');">Kia ĝoja festo (estas hodiaŭ)! </a>
<div id='tr9'><mark>What a joyful feast ([it] is today)!</mark></div></td>

<td align='center' valign='middle'><a id='item10' href='#r2' onclick="toggle_visibility('tr10');">En la tago ni vidas la helan sunon, kaj en la nokto ni vidas la palan lunon kaj la belajn stelojn. </a>
<div id='tr10'><mark>In the day we see the bright sun and in the evening we see the pale moon and the beautiful stars.</mark></div></td>

<td align='center' valign='middle'><a id='item11' href='#r2' onclick="toggle_visibility('tr11');">Ni havas pli freŝan panon, ol vi. </a>
<div id='tr11'><mark>We have fresher bread than you. </mark></div></td>

<td align='center' valign='middle'><a id='item12' href='#r2' onclick="toggle_visibility('tr12');">Ne, vi eraras, sinjoro, via pano estas malpli freŝa, ol mia. </a>
<div id='tr12'><mark>No, you are wrong, Sir, your bread is less fresh than mine.</mark></div></td>
</tr>
<tr id='r4'>

<td align='center' valign='middle'><a id='item13' href='#r3' onclick="toggle_visibility('tr13');">Ni vokas la knabon, kaj li venos. </a>
<div id='tr13'><mark>We call the boy and he comes.</mark></div></td>

<td align='center' valign='middle'><a id='item14' href='#r3' onclick="toggle_visibility('tr14');">En la vintro oni hejtas la fornojn. </a>
<div id='tr14'><mark>In the winter they heat the oven.</mark></div></td>

<td align='center' valign='middle'><a id='item15' href='#r3' onclick="toggle_visibility('tr15');">Kiam oni estas riĉa, oni havas multajn amikojn. </a>
<div id='tr15'><mark>When one is rich, one has many friends.</mark></div></td>

<td align='center' valign='middle'><a id='item16' href='#r3' onclick="toggle_visibility('tr16');">Li amas min, sed mi lin ne amas. </a>
<div id='tr16'><mark>He loves me but I do not love him.</mark></div></td>
</tr>
<tr id='r5'>

<td align='center' valign='middle'><a id='item17' href='#r4' onclick="toggle_visibility('tr17');">Sinjoro P. kaj lia edzino tre amas miajn infanojn; mi ankaŭ tre amas iliajn (infanojn). </a>
<div id='tr17'><mark>Mr. P, and his wife loves my children a lot (very much), I also love theirs (their children) a lot (very much).</mark></div></td>

<td align='center' valign='middle'><a id='item18' href='#r4' onclick="toggle_visibility('tr18');">Mi ne konas la sinjoron, kiu legas.</a>
<div id='tr18'><mark>I do not recognize the gentleman who is reading.</mark></div></td>

</tr>
</table>
<br/>
<p>
<a href=addExercises.html>Return to tabular index of Additional Exerices</a>
</p>

